/**
 * GitHub Updater
 * Automatically updates GitHub issues with UI change analysis
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, '..', 'config');
const SECRETS = JSON.parse(fs.readFileSync(path.join(CONFIG_PATH, 'secrets.json'), 'utf-8'));
const ATTENDEES = JSON.parse(fs.readFileSync(path.join(CONFIG_PATH, 'marta-attendees.json'), 'utf-8'));

const REPO = SECRETS.github.repo || ATTENDEES.integration.github_repo;

/**
 * Execute gh CLI command
 */
function ghCommand(args) {
  try {
    const result = execSync(`gh ${args}`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return result.trim();
  } catch (error) {
    console.error(`gh command failed: ${error.message}`);
    throw error;
  }
}

/**
 * Find existing UI changes issue or get the main Marta issue
 */
async function findRelevantIssue(context = {}) {
  const { meetingTitle = '' } = context;

  try {
    const issues = ghCommand(`issue list -R ${REPO} --state open --json number,title,labels -L 50`);
    const issueList = JSON.parse(issues);

    for (const issue of issueList) {
      const lowerTitle = issue.title.toLowerCase();
      if (lowerTitle.includes('marta') || lowerTitle.includes('beoniq') || lowerTitle.includes('ui')) {
        if (lowerTitle.includes('design') || lowerTitle.includes('dashboard') || lowerTitle.includes('mockup')) {
          return issue;
        }
      }
    }

    for (const issue of issueList) {
      const lowerTitle = issue.title.toLowerCase();
      if (lowerTitle.includes('marta') || lowerTitle.includes('beoniq')) {
        return issue;
      }
    }

    return null;
  } catch (error) {
    console.error('Failed to find issue:', error.message);
    return null;
  }
}

/**
 * Format analysis results as GitHub comment
 */
function formatGitHubComment(options) {
  const { summary, analysisResults, context, mockupPath } = options;
  const timestamp = new Date().toISOString();

  let comment = `## 🎨 UI Changes Detected - ${context.meetingTitle}\n\n`;
  comment += `**Auto-generated:** ${timestamp}\n`;
  comment += `**Confidence:** ${analysisResults.confidence}%\n`;
  comment += `**Persona:** ${context.persona}\n\n`;

  comment += `---\n\n`;
  comment += summary || '';
  comment += `\n\n---\n\n`;

  if (mockupPath) {
    comment += `### Generated Mockup\n`;
    comment += `_Mockup saved locally: \`${mockupPath}\`_\n\n`;
    comment += `To view mockup, check the automation output directory.\n\n`;
  }

  if (analysisResults.relevantSegments && analysisResults.relevantSegments.length > 0) {
    comment += `### Full Transcript Segments\n\n`;
    comment += `<details>\n<summary>Click to expand relevant segments</summary>\n\n`;
    for (const segment of analysisResults.relevantSegments.slice(0, 10)) {
      comment += `> **Line ${segment.lineNumber}:** ${segment.text}\n>\n`;
    }
    comment += `\n</details>\n\n`;
  }

  comment += `---\n`;
  comment += `_Generated by Marta UI Watcher automation_`;

  return comment;
}

/**
 * Update existing GitHub issue with UI changes
 */
async function updateGitHubIssue(options) {
  const { summary, mockupPath, analysisResults, context } = options;

  const issue = await findRelevantIssue(context);

  if (!issue) {
    console.log('No relevant issue found, creating new one');
    return createGitHubIssue(options);
  }

  const comment = formatGitHubComment({ summary, analysisResults, context, mockupPath });

  const escapedComment = comment.replace(/'/g, "'\\''");

  try {
    ghCommand(`issue comment ${issue.number} -R ${REPO} --body '${escapedComment}'`);

    const issueUrl = `https://github.com/${REPO}/issues/${issue.number}`;
    console.log(`Updated issue #${issue.number}: ${issueUrl}`);

    return {
      issueNumber: issue.number,
      url: issueUrl,
      action: 'commented',
    };
  } catch (error) {
    console.error('Failed to comment on issue:', error.message);
    throw error;
  }
}

/**
 * Create new GitHub issue for UI changes
 */
async function createGitHubIssue(options) {
  const { summary, mockupPath, analysisResults, context } = options;

  const title = `[Marta UI] Changes from ${context.meetingTitle} - ${new Date().toLocaleDateString()}`;

  let body = `## UI Changes Detected\n\n`;
  body += `**Meeting:** ${context.meetingTitle}\n`;
  body += `**Date:** ${new Date().toISOString()}\n`;
  body += `**Persona:** ${context.persona}\n`;
  body += `**Confidence:** ${analysisResults.confidence}%\n\n`;
  body += `---\n\n`;
  body += summary || 'No detailed summary available.';

  if (analysisResults.extractedChanges && analysisResults.extractedChanges.length > 0) {
    body += `\n\n### Action Items\n\n`;
    for (const change of analysisResults.extractedChanges.slice(0, 10)) {
      body += `- [ ] ${change.fullMatch}\n`;
    }
  }

  body += `\n\n---\n_Auto-generated by Marta UI Watcher_`;

  const escapedTitle = title.replace(/'/g, "'\\''");
  const escapedBody = body.replace(/'/g, "'\\''");

  try {
    const result = ghCommand(`issue create -R ${REPO} --title '${escapedTitle}' --body '${escapedBody}' --label 'marta,ui,auto-generated'`);

    const urlMatch = result.match(/https:\/\/github\.com\/[^\s]+/);
    const url = urlMatch ? urlMatch[0] : result;
    const numberMatch = url.match(/\/issues\/(\d+)/);
    const issueNumber = numberMatch ? parseInt(numberMatch[1]) : null;

    console.log(`Created issue: ${url}`);

    return {
      issueNumber,
      url,
      action: 'created',
    };
  } catch (error) {
    console.error('Failed to create issue:', error.message);
    throw error;
  }
}

/**
 * Add transcript to existing issue
 */
async function addTranscriptToIssue(issueNumber, transcript, meetingTitle) {
  const timestamp = new Date().toISOString();

  let comment = `## 📝 Full Transcript - ${meetingTitle}\n\n`;
  comment += `**Added:** ${timestamp}\n\n`;
  comment += `<details>\n<summary>Click to expand full transcript</summary>\n\n`;
  comment += `\`\`\`\n${transcript.substring(0, 60000)}\n\`\`\`\n`;
  if (transcript.length > 60000) {
    comment += `\n_Transcript truncated (${transcript.length} total characters)_\n`;
  }
  comment += `\n</details>`;

  const escapedComment = comment.replace(/'/g, "'\\''");

  try {
    ghCommand(`issue comment ${issueNumber} -R ${REPO} --body '${escapedComment}'`);
    console.log(`Added transcript to issue #${issueNumber}`);
    return true;
  } catch (error) {
    console.error('Failed to add transcript:', error.message);
    return false;
  }
}

module.exports = {
  updateGitHubIssue,
  createGitHubIssue,
  findRelevantIssue,
  addTranscriptToIssue,
  ghCommand,
};
